@startuml
left to right direction
skinparam shadowing false
skinparam packageStyle rectangle
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor white
  BorderColor #444444
  ArrowColor #666666
}
skinparam rectangle {
  BorderColor #444444
}

actor "usuario configurador" as UsuarioConfigurador

rectangle "Sistema-alvo / engine futura" {
  usecase "CriarPipeline" as UC_CriarPipeline
  usecase "ListarPipelines" as UC_ListarPipelines
  usecase "EditarPipeline" as UC_EditarPipeline
  usecase "ExecutarPipelineDocumental" as UC_ExecutarPipelineDocumental
  usecase "PersistirProdutosDerivados" as UC_PersistirProdutosDerivados
  usecase "RevisarTraducao" as UC_RevisarTraducao
}

UsuarioConfigurador --> UC_CriarPipeline
UsuarioConfigurador --> UC_ListarPipelines
UsuarioConfigurador --> UC_EditarPipeline
UsuarioConfigurador --> UC_ExecutarPipelineDocumental
UsuarioConfigurador --> UC_PersistirProdutosDerivados
UsuarioConfigurador --> UC_RevisarTraducao

@enduml
